completed
learn-academy-2023-bravo/week-1-assessment-FLopez73 pull request #1
Opened 2023-03-20 03:47 UTC by FLopez73

# Submitting Week 1 Assessment

### ✅ Completed Files

Select the following as confirmation that the files in this repository are complete.

- [x ] Coding Challenges
- [x ] Coding Concepts
- [ x] Interview Questions

### 📝 Feedback

If you would like specific feedback on a particular problem please leave details here:

2023-03-21 22:03 UTC, Genemichael25 requested changes
Felix, this is a very solid start to these assessments! I love the pseudocode you provided for # 1 on the code challenges but I am requesting changes for missing pseudocode in # 4 and 5 in code challenges. You can briefly mention the methods you intend to use and their output, or how they will work for your approach. Also, need a researched answer for # 2 in the interview questions section. Left a comment to help you expand on that, as well as a few more throughout for you to consider. Please make the changes and push up on the same branch and notify me so I can finish reviewing and approve the PR. Any questions, don't hesitate to reach out!

2023-03-21 22:03 UTC, Genemichael25 commented on code-challenges.js
> +//it returns a string with a inperpolation syntax to include input letting user know if above, below or at boiling.
Great job on this pseudocode! I love that you mention string interpolation and how you intend to use it!! 💯

2023-03-21 22:03 UTC, Genemichael25 commented on code-challenges.js
> +//output:3202 ovarB
Nice job! Why did you use ('') in the split and join methods?

2023-03-21 22:03 UTC, Genemichael25 commented on code-challenges.js
> +const tempTwo = (sanDiegoWinterTemperatures.sort().reverse())
Awesome! Great job getting the output you expected!! Sort allows us to pass a function that will change the way it sorts and reverse might not even be necessary if you want to check that out. Missing pseudocode for this problem.

2023-03-21 22:03 UTC, Genemichael25 commented on coding-concepts.js
> +// b) Verify and explain:Error .toUpperCase() is a string property that is not applicable to the array since they return values.
Nice follow up! It is important to note which methods work on what data types.

2023-03-21 22:03 UTC, Genemichael25 commented on coding-concepts.js
> +// b) Verify and explain:number due to the "typeof" operator which checks the type of operand's value which is an array that only returns numbers.
typeof in this scenario is giving you the data type which results from using .length on the array

2023-03-21 22:03 UTC, Genemichael25 commented on interview-questions.md
> +Researched answer:
Missing researched answer, would be a great spot to expand on current knowledge as well as use examples.

2023-03-21 22:03 UTC, Genemichael25 commented on code-challenges.js
Need pseudocode for this problem. You can mention the method you intend on using and how it works.

2023-03-21 22:03 UTC, Genemichael25 commented on code-challenges.js
> +console.log(boilingPoint (212)) //212 at boiling point
You can pass the variables as arguments here.

2023-03-22 05:06 UTC, FLopez73 commented
Hey Gene! Thank you for all the feedback it was very helpful. I don't know how I completely missed some questions lol. I have pushed the updated assessment let me know if you can see it.

2023-03-22 05:36 UTC, FLopez73 commented on code-challenges.js
> +const tempTwo = (sanDiegoWinterTemperatures.sort().reverse())
I get what you mean by this now after I submitted by updates. The .sort() method can take a comparison function as an argument in order to set the descending order which would be (a,b) => b-a.

2023-03-23 05:19 UTC, Genemichael25 approved these changes
Thanks for making those changes! Continue to use pseudocode and break down the problems to help you get to that next level. This assessment currently displays a novice level of comprehension and is a great start, keep up the good work!

2023-03-24 16:15 UTC, merged